import { AnchorProvider, Program } from "@coral-xyz/anchor";
import { Connection, PublicKey } from "@solana/web3.js";
import type { AnchorWallet } from "@solana/wallet-adapter-react";
import { PROGRAM_IDS, RPC_ENDPOINT } from "./constants";

import RiseStakingIdl from "./idls/rise_staking.json";
import RiseCdpIdl     from "./idls/rise_cdp.json";
import RiseGovIdl     from "./idls/rise_governance.json";
import RiseRewardsIdl from "./idls/rise_rewards.json";

// IDL types generated by `anchor build` — kept in the protocol repo and
// imported here as plain JSON (resolveJsonModule: true in tsconfig).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyIdl = any;

export function getProvider(wallet: AnchorWallet, endpoint = RPC_ENDPOINT): AnchorProvider {
  const connection = new Connection(endpoint, "confirmed");
  return new AnchorProvider(connection, wallet, { commitment: "confirmed" });
}

export function getStakingProgram(provider: AnchorProvider): Program {
  return new Program(RiseStakingIdl as AnyIdl, provider);
}

export function getCdpProgram(provider: AnchorProvider): Program {
  return new Program(RiseCdpIdl as AnyIdl, provider);
}

export function getGovernanceProgram(provider: AnchorProvider): Program {
  return new Program(RiseGovIdl as AnyIdl, provider);
}

export function getRewardsProgram(provider: AnchorProvider): Program {
  return new Program(RiseRewardsIdl as AnyIdl, provider);
}

export function getProgramPublicKeys() {
  return {
    staking:    new PublicKey(PROGRAM_IDS.RISE_STAKING),
    cdp:        new PublicKey(PROGRAM_IDS.RISE_CDP),
    governance: new PublicKey(PROGRAM_IDS.RISE_GOVERNANCE),
    rewards:    new PublicKey(PROGRAM_IDS.RISE_REWARDS),
  };
}
